referenceless_regression_metric:
  class_path: comet.models.ReferencelessRegression
  init_args:
    nr_frozen_epochs: 0.3
    keep_embeddings_frozen: True
    optimizer: AdamW
    encoder_learning_rate: 1.0e-06
    learning_rate: 1.5e-05
    layerwise_decay: 0.95
    encoder_model: ModernBERT
    pretrained_model: answerdotai/ModernBERT-large
    pool: cls
    layer: mix
    layer_transformation: sparsemax
    layer_norm: False
    loss: mse
    dropout: 0.1
    batch_size: 8
    train_data: 
      - data/csv/train_da.csv
    validation_data: 
      - data/csv/dev_da.csv
    hidden_sizes:
      - 2048
      - 1024
    activations: Tanh
    
trainer: trainer.yaml
early_stopping: baseline_early_stopping.yaml
model_checkpoint: baseline_model_checkpoint.yaml